### ISSUE TITLE
Research email law and follow all applicable laws related to email subscriptions

### ISSUE THREAD

**Issue by ah593** [NJIT-WIS/project-2-is219-wwc#16]

**Comment by DemiScript** [comment]
## Email Subscriptions Best Practices
1. Obtain explicit consent: You must obtain explicit and freely given consent from individuals to collect and process their personal data. This means that you must clearly inform them about the data you collect, why you collect it, and how you will use it.
2. Provide a clear privacy policy: You must provide a clear and concise privacy policy that explains your data collection and processing practices. Your policy should outline the types of data you collect, how you use it, and who you share it with.
3. Offer a clear opt-in process: You must provide a clear and prominent opt-in process for individuals to subscribe to your newsletter. This should include a checkbox or similar mechanism that clearly indicates their consent to receive marketing communications.
4. Provide an easy opt-out process: You must provide an easy opt-out process for individuals to unsubscribe from your newsletter. This should be clearly visible and easy to use.
5. Keep records of consent: You must keep records of consent from individuals, including the time and date they provided consent and the specific data they consented to have collected and processed.
6. Ensure data security: You must implement appropriate data security measures to protect the personal data you collect and process, such as encryption and access controls.
7. Limit data retention: You must limit the amount of time you retain personal data to only what is necessary to fulfill the purposes for which it was collected.
